version: '3'

services:
  db:
    image: 'mysql:latest'
    ports:
           - "3307:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=tpachato
    volumes:
           - /home/vagrant/mysql:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backend:
    image: 'slowwsloth/zied_cicd_back:latest'
    ports:
           - "8089:8089"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    image: 'slowwsloth/zied_cicd_front:latest'
    links:
           - "backend"
    depends_on:
           - "backend"
    ports:
           - "88:80"
